const IDENTIFIERS = {
  SFC_COMPILER: Symbol('SFC_COMPILER'),
  SSSA_COMPILER: Symbol('SSSA_COMPILER'),
  TEMPLATE_COMPILER: Symbol('TEMPLATE_COMPILER'),
  SFC_LOADER: Symbol('SFC_LOADER'),
  SSSA_LOADER: Symbol('SSSA_LOADER'),
  TEMPLATE_LOADER: Symbol('TEMPLATE_LOADER'),
  NETWORK: Symbol('NETWORK'),
};

export default IDENTIFIERS;